### ISSUE TITLE
版本依赖问题

### ISSUE THREAD

**Issue by jaredtech** [MikaelZero/Piko#1]
获取依赖库的时候，Running "flutter pub get" in Piko...

Because every version of flutter_test from sdk depends on path 1.6.4 and flutter_launcher_icons 0.8.1 depends on path ^1.7.0, flutter_test from sdk is incompatible with flutter_launcher_icons 0.8.1.

And because no versions of flutter_launcher_icons match >0.8.1 <0.9.0, flutter_test from sdk is incompatible with flutter_launcher_icons ^0.8.1.

So, because pixiv depends on both flutter_launcher_icons ^0.8.1 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because pixiv depends on both flutter_launcher_icons ^0.8.1 and flutter_test any from sdk, version solving failed.)

是不是在readme发一下开发环境

**Comment by MikaelZero** [comment]
感谢提醒  
flutter 版本为 1.23.0-18.1.pre
